slots:
  - room: "H1123"
    disambiguate: 0
    capacity: 30
    mappings:
      - course: literature
        class: "1BHIT"
    start: 4
    weekday: "saturday"
    duration: 2
    supervisors:
      - prof._elaine_brooks
      - scheduler_admin
